### ISSUE TITLE
OpenApiUiExtension not working with OpenApiMP

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee-openapi-mp#1]
I've tried to enable OpenApiUiExtension with OpenApiMPExtension and it doesn't work.

An error message is generated at startup:
`2020-02-17 11:00:42.720 SEVERE -- com.kumuluz.ee.openapi.ui.OpenApiUiExtension -- Unable to find OpenApi extension, OpenAPI UI will not be initialized: com.kumuluz.ee.openapi.OpenApiExtension`

Regarding the code, [OpenApiUIExtension](https://github.com/kumuluz/kumuluzee-openapi/blob/master/openapi-ui/src/main/java/com/kumuluz/ee/openapi/ui/OpenApiUiExtension.java) does a Class.forName on OpenAPIExtension and refuse to start if NOK.

As a workaround,  I've added OpenAPiExtension as a dependency but it is incompatible with OpenAPIMPExtension:
`2020-02-17 11:45:57.606 SEVERE -- com.kumuluz.ee.EeApplication -- Found multiple implementations (OpenAPI, OpenApiMp) of the same EE extension group (OPEN_API). Please check to make sure you only include a single implementation of a specific EE extension group.`

So, it seems there is no way to use OpenApiUIExtension with OpenApiMPExtension.

**Comment by MBJuric** [comment]
Hi,
For OpenApiMPExtension, you need to use OpenApi**Mp**UiExtension (and not OpenApiUiExtension).
The Maven dependency has to be `kumuluzee-openapi-mp-ui`
Please let us know if you have any further problems.

**Comment by jefrajames** [comment]
You're fully true and it is written in the doc: https://github.com/kumuluz/kumuluzee-openapi-mp. I should have read it. Sorry for the inconvenience. KumuluzEE rocks!
