### ISSUE TITLE
NPE due to Swagger UI when testing with Arquillian

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee-openapi-mp#2]
I'm using KumuluzEE 3.7.0. I'm working on a MicroProfile 3.2 project using JAX-RS. 

I've added Swagger UI in my pom.xml:  _com.kumuluz.ee.openapi:kumuluzee-openapi-mp-ui:1.1.2_

When running an Arquillian test, a NullPointerException is thrown at application startup if I do not add JAX-RS classes in my deployment:

> com.kumuluz.ee.openapi.mp.ui.OpenApiMpUiExtension -- Initializing OpenAPI MP UI extension.
Exception in thread "main" java.lang.NullPointerException
	at com.kumuluz.ee.openapi.mp.ui.OpenApiMpUiExtension.init(OpenApiMpUiExtension.java:97)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:367)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:73)
	at com.kumuluz.ee.testing.arquillian.assets.MainWrapper.main(MainWrapper.java:52)

As a workaround, I've to add the JAX-RS classes in my deployment even if I don't need them in the tests:
> archive.addPackages(false, Filters.exclude(".*Test.*"), RestApplication.class.getPackage());

The symptom is the same when disabling the UI in the config:
`openapi:
    ui:
      enabled: false`

**Comment by zvonegit** [comment]
Hi @jefrajames,

Can you share more about your Arquillian container configuration (arquillian.xml), the includeRequiredLibraries part?

By default, Arquillian will start the container with 'kumuluzee-core', 'kumuluzee-servlet-jetty' and 'kumuluzee-cdi-weld'. The OpenAPI library expects jax-rs implementation in the runtime (kumuluzee-jax-rs-jersey). It is not included in the library itself, it has to be provided in the container. I assume this is the issue. It should be resolved by setting the includeRequiredLibraries to one of the options mentioned [here](https://github.com/kumuluz/kumuluzee-testing/tree/master/kumuluzee-arquillian-container#configuring-arquillian-container-adapter).

Let me know if this solves your issue.

**Comment by cen1** [comment]
Server definition can fall back to either kumuluzee.server.base-url or specification server config in openapi configuration subset so we do not have to rely on smallrye instance to have it populated in any case. Added NPE check, pending review.

**Comment by cen1** [comment]
merged
