### ISSUE TITLE
Array of enums is not intepreted correctly in object examples in openapi (html)

### ISSUE THREAD

**Issue by mivr83** [kumuluz/kumuluzee-openapi-mp#4]
Lets say we have DTO with field like this: 
`List<SOME_ENUM> listOfEnums`

When viewed in web, list is shown as array of **objects**, example object in array is empty and when enum contains fileds then this object contains this field(s).

See https://stackoverflow.com/questions/36888626/defining-enum-for-array-in-swagger-2-0, here it is prty nicely covered in answer what would i expect to see in swagger/openapi.

**Comment by cen1** [comment]
Is this what you would expect? 

<img width="265" alt="Screenshot 2020-04-07 at 19 07 56" src="https://user-images.githubusercontent.com/1158861/78698805-2b81a180-7903-11ea-9e75-298d900a1d54.png">

It seems this was fixed in upstream, we will update the dependency versions in the following days.
