### ISSUE TITLE
Automatic configuration

### ISSUE THREAD

**Issue by mivr83** [kumuluz/kumuluzee-openapi-mp#6]
We have issue with openapi-mp project - we are lacking feature which automatically sets proper redirect path and server. We have solution - dynamically resolving host:port and setting proper redirect path and adding corresponding server into list of servers, so after hiting /api-specs url swagger is ready to use without need to set config for every environment.

Idea is to make it by default disabled (so existing projects will be not broken) and when enabled then it takes over static configuration a sets all cofiguration based on information from request.

Its also possible to resolve path 'hiden' by for example Ingres (if exposed path is provided in header).

I would welcom some opinion(s) on this feature and/or green light to proceed with pull request.

**Comment by MBJuric** [comment]
Hello,
This is a great idea, the feature is useful. Please proceed with the pull request.
Thanks in advance.

**Comment by mivr83** [comment]
Here is promised pull request: #7
